/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AIRules
 */
export interface AIRules {
    /**
     * 
     * @type {Array<string>}
     * @memberof AIRules
     */
    disallowedAgents?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AIRules
     */
    allowedAgents?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AIRules
     */
    disallowedPaths?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AIRules
     */
    allowedPaths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AIRules
     */
    generalAccess?: AIRulesGeneralAccessEnum;
}


/**
 * @export
 */
export const AIRulesGeneralAccessEnum = {
    Unknown: 'unknown',
    Restricted: 'restricted',
    Allowed: 'allowed',
    Mixed: 'mixed'
} as const;
export type AIRulesGeneralAccessEnum = typeof AIRulesGeneralAccessEnum[keyof typeof AIRulesGeneralAccessEnum];


/**
 * Check if a given object implements the AIRules interface.
 */
export function instanceOfAIRules(value: object): value is AIRules {
    return true;
}

export function AIRulesFromJSON(json: any): AIRules {
    return AIRulesFromJSONTyped(json, false);
}

export function AIRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIRules {
    if (json == null) {
        return json;
    }
    return {
        
        'disallowedAgents': json['disallowed_agents'] == null ? undefined : json['disallowed_agents'],
        'allowedAgents': json['allowed_agents'] == null ? undefined : json['allowed_agents'],
        'disallowedPaths': json['disallowed_paths'] == null ? undefined : json['disallowed_paths'],
        'allowedPaths': json['allowed_paths'] == null ? undefined : json['allowed_paths'],
        'generalAccess': json['general_access'] == null ? undefined : json['general_access'],
    };
}

export function AIRulesToJSON(json: any): AIRules {
    return AIRulesToJSONTyped(json, false);
}

export function AIRulesToJSONTyped(value?: AIRules | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disallowed_agents': value['disallowedAgents'],
        'allowed_agents': value['allowedAgents'],
        'disallowed_paths': value['disallowedPaths'],
        'allowed_paths': value['allowedPaths'],
        'general_access': value['generalAccess'],
    };
}
