/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluationDetailsResponse
 */
export interface EvaluationDetailsResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof EvaluationDetailsResponse
     */
    imageJudgeRecord: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsResponse
     */
    keyPoints: string;
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsResponse
     */
    inputText: string;
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsResponse
     */
    systemMsg: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof EvaluationDetailsResponse
     */
    evaluationDetails: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof EvaluationDetailsResponse
     */
    predictedLabel: number;
}

/**
 * Check if a given object implements the EvaluationDetailsResponse interface.
 */
export function instanceOfEvaluationDetailsResponse(value: object): value is EvaluationDetailsResponse {
    if (!('imageJudgeRecord' in value) || value['imageJudgeRecord'] === undefined) return false;
    if (!('keyPoints' in value) || value['keyPoints'] === undefined) return false;
    if (!('inputText' in value) || value['inputText'] === undefined) return false;
    if (!('systemMsg' in value) || value['systemMsg'] === undefined) return false;
    if (!('evaluationDetails' in value) || value['evaluationDetails'] === undefined) return false;
    if (!('predictedLabel' in value) || value['predictedLabel'] === undefined) return false;
    return true;
}

export function EvaluationDetailsResponseFromJSON(json: any): EvaluationDetailsResponse {
    return EvaluationDetailsResponseFromJSONTyped(json, false);
}

export function EvaluationDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageJudgeRecord': json['image_judge_record'],
        'keyPoints': json['key_points'],
        'inputText': json['input_text'],
        'systemMsg': json['system_msg'],
        'evaluationDetails': json['evaluation_details'],
        'predictedLabel': json['predicted_label'],
    };
}

export function EvaluationDetailsResponseToJSON(json: any): EvaluationDetailsResponse {
    return EvaluationDetailsResponseToJSONTyped(json, false);
}

export function EvaluationDetailsResponseToJSONTyped(value?: EvaluationDetailsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_judge_record': value['imageJudgeRecord'],
        'key_points': value['keyPoints'],
        'input_text': value['inputText'],
        'system_msg': value['systemMsg'],
        'evaluation_details': value['evaluationDetails'],
        'predicted_label': value['predictedLabel'],
    };
}
