/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluationDetailsRequest
 */
export interface EvaluationDetailsRequest {
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsRequest
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsRequest
     */
    taskDescription: string;
    /**
     * 
     * @type {string}
     * @memberof EvaluationDetailsRequest
     */
    finalResultResponse?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvaluationDetailsRequest
     */
    actionHistory?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvaluationDetailsRequest
     */
    thoughts?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvaluationDetailsRequest
     */
    screenshots: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvaluationDetailsRequest
     */
    inputImagePaths?: Array<string> | null;
}

/**
 * Check if a given object implements the EvaluationDetailsRequest interface.
 */
export function instanceOfEvaluationDetailsRequest(value: object): value is EvaluationDetailsRequest {
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('taskDescription' in value) || value['taskDescription'] === undefined) return false;
    if (!('screenshots' in value) || value['screenshots'] === undefined) return false;
    return true;
}

export function EvaluationDetailsRequestFromJSON(json: any): EvaluationDetailsRequest {
    return EvaluationDetailsRequestFromJSONTyped(json, false);
}

export function EvaluationDetailsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationDetailsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
        'taskDescription': json['task_description'],
        'finalResultResponse': json['final_result_response'] == null ? undefined : json['final_result_response'],
        'actionHistory': json['action_history'] == null ? undefined : json['action_history'],
        'thoughts': json['thoughts'] == null ? undefined : json['thoughts'],
        'screenshots': json['screenshots'],
        'inputImagePaths': json['input_image_paths'] == null ? undefined : json['input_image_paths'],
    };
}

export function EvaluationDetailsRequestToJSON(json: any): EvaluationDetailsRequest {
    return EvaluationDetailsRequestToJSONTyped(json, false);
}

export function EvaluationDetailsRequestToJSONTyped(value?: EvaluationDetailsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
        'task_description': value['taskDescription'],
        'final_result_response': value['finalResultResponse'],
        'action_history': value['actionHistory'],
        'thoughts': value['thoughts'],
        'screenshots': value['screenshots'],
        'input_image_paths': value['inputImagePaths'],
    };
}

