/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunEvent } from './RunEvent';
import {
    RunEventFromJSON,
    RunEventFromJSONTyped,
    RunEventToJSON,
    RunEventToJSONTyped,
} from './RunEvent';

/**
 * 
 * @export
 * @interface ListEvents200Response
 */
export interface ListEvents200Response {
    /**
     * 
     * @type {Array<RunEvent>}
     * @memberof ListEvents200Response
     */
    items?: Array<RunEvent>;
    /**
     * 
     * @type {string}
     * @memberof ListEvents200Response
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the ListEvents200Response interface.
 */
export function instanceOfListEvents200Response(value: object): value is ListEvents200Response {
    return true;
}

export function ListEvents200ResponseFromJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseFromJSONTyped(json, false);
}

export function ListEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(RunEventFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function ListEvents200ResponseToJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseToJSONTyped(json, false);
}

export function ListEvents200ResponseToJSONTyped(value?: ListEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(RunEventToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

