/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AIRules } from './AIRules';
import {
    AIRulesFromJSON,
    AIRulesFromJSONTyped,
    AIRulesToJSON,
    AIRulesToJSONTyped,
} from './AIRules';

/**
 * 
 * @export
 * @interface RobotsAnalysisResponse
 */
export interface RobotsAnalysisResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RobotsAnalysisResponse
     */
    hasRobotsTxt?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RobotsAnalysisResponse
     */
    robotsUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RobotsAnalysisResponse
     */
    robotsContent?: string | null;
    /**
     * 
     * @type {AIRules}
     * @memberof RobotsAnalysisResponse
     */
    aiRules?: AIRules;
    /**
     * 
     * @type {string}
     * @memberof RobotsAnalysisResponse
     */
    llmSuggestions?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RobotsAnalysisResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the RobotsAnalysisResponse interface.
 */
export function instanceOfRobotsAnalysisResponse(value: object): value is RobotsAnalysisResponse {
    return true;
}

export function RobotsAnalysisResponseFromJSON(json: any): RobotsAnalysisResponse {
    return RobotsAnalysisResponseFromJSONTyped(json, false);
}

export function RobotsAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotsAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasRobotsTxt': json['has_robots_txt'] == null ? undefined : json['has_robots_txt'],
        'robotsUrl': json['robots_url'] == null ? undefined : json['robots_url'],
        'robotsContent': json['robots_content'] == null ? undefined : json['robots_content'],
        'aiRules': json['ai_rules'] == null ? undefined : AIRulesFromJSON(json['ai_rules']),
        'llmSuggestions': json['llm_suggestions'] == null ? undefined : json['llm_suggestions'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function RobotsAnalysisResponseToJSON(json: any): RobotsAnalysisResponse {
    return RobotsAnalysisResponseToJSONTyped(json, false);
}

export function RobotsAnalysisResponseToJSONTyped(value?: RobotsAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_robots_txt': value['hasRobotsTxt'],
        'robots_url': value['robotsUrl'],
        'robots_content': value['robotsContent'],
        'ai_rules': AIRulesToJSON(value['aiRules']),
        'llm_suggestions': value['llmSuggestions'],
        'error': value['error'],
    };
}

