/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunSummaryLinks
 */
export interface RunSummaryLinks {
    /**
     * 
     * @type {string}
     * @memberof RunSummaryLinks
     */
    score?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSummaryLinks
     */
    events?: string;
}

/**
 * Check if a given object implements the RunSummaryLinks interface.
 */
export function instanceOfRunSummaryLinks(value: object): value is RunSummaryLinks {
    return true;
}

export function RunSummaryLinksFromJSON(json: any): RunSummaryLinks {
    return RunSummaryLinksFromJSONTyped(json, false);
}

export function RunSummaryLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSummaryLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'events': json['events'] == null ? undefined : json['events'],
    };
}

export function RunSummaryLinksToJSON(json: any): RunSummaryLinks {
    return RunSummaryLinksToJSONTyped(json, false);
}

export function RunSummaryLinksToJSONTyped(value?: RunSummaryLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'events': value['events'],
    };
}

