/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentStatus
 */
export interface AgentStatus {
    /**
     * 
     * @type {string}
     * @memberof AgentStatus
     */
    runId: string;
    /**
     * 
     * @type {string}
     * @memberof AgentStatus
     */
    status: AgentStatusStatusEnum;
}


/**
 * @export
 */
export const AgentStatusStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type AgentStatusStatusEnum = typeof AgentStatusStatusEnum[keyof typeof AgentStatusStatusEnum];


/**
 * Check if a given object implements the AgentStatus interface.
 */
export function instanceOfAgentStatus(value: object): value is AgentStatus {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AgentStatusFromJSON(json: any): AgentStatus {
    return AgentStatusFromJSONTyped(json, false);
}

export function AgentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'],
        'status': json['status'],
    };
}

export function AgentStatusToJSON(json: any): AgentStatus {
    return AgentStatusToJSONTyped(json, false);
}

export function AgentStatusToJSONTyped(value?: AgentStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'status': value['status'],
    };
}

