/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentSuccessMetrics
 */
export interface AgentSuccessMetrics {
    /**
     * 
     * @type {number}
     * @memberof AgentSuccessMetrics
     */
    numSteps?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentSuccessMetrics
     */
    timeToCompletionMs?: number;
    /**
     * Retries when LLM-as-judge flags wrong metric/step.
     * @type {number}
     * @memberof AgentSuccessMetrics
     */
    numRetries?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AgentSuccessMetrics
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AgentSuccessMetrics
     */
    llmTokens?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentSuccessMetrics
     */
    cpuUsagePct?: number;
}

/**
 * Check if a given object implements the AgentSuccessMetrics interface.
 */
export function instanceOfAgentSuccessMetrics(value: object): value is AgentSuccessMetrics {
    return true;
}

export function AgentSuccessMetricsFromJSON(json: any): AgentSuccessMetrics {
    return AgentSuccessMetricsFromJSONTyped(json, false);
}

export function AgentSuccessMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSuccessMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'numSteps': json['num_steps'] == null ? undefined : json['num_steps'],
        'timeToCompletionMs': json['time_to_completion_ms'] == null ? undefined : json['time_to_completion_ms'],
        'numRetries': json['num_retries'] == null ? undefined : json['num_retries'],
        'success': json['success'] == null ? undefined : json['success'],
        'llmTokens': json['llm_tokens'] == null ? undefined : json['llm_tokens'],
        'cpuUsagePct': json['cpu_usage_pct'] == null ? undefined : json['cpu_usage_pct'],
    };
}

export function AgentSuccessMetricsToJSON(json: any): AgentSuccessMetrics {
    return AgentSuccessMetricsToJSONTyped(json, false);
}

export function AgentSuccessMetricsToJSONTyped(value?: AgentSuccessMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'num_steps': value['numSteps'],
        'time_to_completion_ms': value['timeToCompletionMs'],
        'num_retries': value['numRetries'],
        'success': value['success'],
        'llm_tokens': value['llmTokens'],
        'cpu_usage_pct': value['cpuUsagePct'],
    };
}

