/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RobotsAnalysisResponse
 */
export interface RobotsAnalysisResponse {
    /**
     * 
     * @type {number}
     * @memberof RobotsAnalysisResponse
     */
    numOkayPages?: number;
    /**
     * 
     * @type {number}
     * @memberof RobotsAnalysisResponse
     */
    numNotOkayPages?: number;
    /**
     * 
     * @type {string}
     * @memberof RobotsAnalysisResponse
     */
    overallSentiment?: RobotsAnalysisResponseOverallSentimentEnum;
}


/**
 * @export
 */
export const RobotsAnalysisResponseOverallSentimentEnum = {
    Permissive: 'permissive',
    Mixed: 'mixed',
    Restrictive: 'restrictive'
} as const;
export type RobotsAnalysisResponseOverallSentimentEnum = typeof RobotsAnalysisResponseOverallSentimentEnum[keyof typeof RobotsAnalysisResponseOverallSentimentEnum];


/**
 * Check if a given object implements the RobotsAnalysisResponse interface.
 */
export function instanceOfRobotsAnalysisResponse(value: object): value is RobotsAnalysisResponse {
    return true;
}

export function RobotsAnalysisResponseFromJSON(json: any): RobotsAnalysisResponse {
    return RobotsAnalysisResponseFromJSONTyped(json, false);
}

export function RobotsAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RobotsAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'numOkayPages': json['num_okay_pages'] == null ? undefined : json['num_okay_pages'],
        'numNotOkayPages': json['num_not_okay_pages'] == null ? undefined : json['num_not_okay_pages'],
        'overallSentiment': json['overall_sentiment'] == null ? undefined : json['overall_sentiment'],
    };
}

export function RobotsAnalysisResponseToJSON(json: any): RobotsAnalysisResponse {
    return RobotsAnalysisResponseToJSONTyped(json, false);
}

export function RobotsAnalysisResponseToJSONTyped(value?: RobotsAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'num_okay_pages': value['numOkayPages'],
        'num_not_okay_pages': value['numNotOkayPages'],
        'overall_sentiment': value['overallSentiment'],
    };
}

