/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunEvent
 */
export interface RunEvent {
    /**
     * 
     * @type {Date}
     * @memberof RunEvent
     */
    ts?: Date;
    /**
     * 
     * @type {string}
     * @memberof RunEvent
     */
    step?: string;
    /**
     * 
     * @type {string}
     * @memberof RunEvent
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof RunEvent
     */
    status?: RunEventStatusEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RunEvent
     */
    details?: { [key: string]: any; };
}


/**
 * @export
 */
export const RunEventStatusEnum = {
    Ok: 'ok',
    Retry: 'retry',
    Fail: 'fail'
} as const;
export type RunEventStatusEnum = typeof RunEventStatusEnum[keyof typeof RunEventStatusEnum];


/**
 * Check if a given object implements the RunEvent interface.
 */
export function instanceOfRunEvent(value: object): value is RunEvent {
    return true;
}

export function RunEventFromJSON(json: any): RunEvent {
    return RunEventFromJSONTyped(json, false);
}

export function RunEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'ts': json['ts'] == null ? undefined : (new Date(json['ts'])),
        'step': json['step'] == null ? undefined : json['step'],
        'action': json['action'] == null ? undefined : json['action'],
        'status': json['status'] == null ? undefined : json['status'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function RunEventToJSON(json: any): RunEvent {
    return RunEventToJSONTyped(json, false);
}

export function RunEventToJSONTyped(value?: RunEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ts': value['ts'] == null ? undefined : ((value['ts']).toISOString()),
        'step': value['step'],
        'action': value['action'],
        'status': value['status'],
        'details': value['details'],
    };
}

