/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreArtifactsInner
 */
export interface ScoreArtifactsInner {
    /**
     * 
     * @type {string}
     * @memberof ScoreArtifactsInner
     */
    kind?: ScoreArtifactsInnerKindEnum;
    /**
     * 
     * @type {string}
     * @memberof ScoreArtifactsInner
     */
    url?: string;
}


/**
 * @export
 */
export const ScoreArtifactsInnerKindEnum = {
    Screenshot: 'screenshot',
    Dom: 'dom',
    Log: 'log',
    Rrweb: 'rrweb'
} as const;
export type ScoreArtifactsInnerKindEnum = typeof ScoreArtifactsInnerKindEnum[keyof typeof ScoreArtifactsInnerKindEnum];


/**
 * Check if a given object implements the ScoreArtifactsInner interface.
 */
export function instanceOfScoreArtifactsInner(value: object): value is ScoreArtifactsInner {
    return true;
}

export function ScoreArtifactsInnerFromJSON(json: any): ScoreArtifactsInner {
    return ScoreArtifactsInnerFromJSONTyped(json, false);
}

export function ScoreArtifactsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreArtifactsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ScoreArtifactsInnerToJSON(json: any): ScoreArtifactsInner {
    return ScoreArtifactsInnerToJSONTyped(json, false);
}

export function ScoreArtifactsInnerToJSONTyped(value?: ScoreArtifactsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'url': value['url'],
    };
}

