/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSessionResponse
 */
export interface CreateSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    sessionUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    debuggerFullscreenUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    debuggerUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    wsUrl: string;
}

/**
 * Check if a given object implements the CreateSessionResponse interface.
 */
export function instanceOfCreateSessionResponse(value: object): value is CreateSessionResponse {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('sessionUrl' in value) || value['sessionUrl'] === undefined) return false;
    if (!('debuggerFullscreenUrl' in value) || value['debuggerFullscreenUrl'] === undefined) return false;
    if (!('debuggerUrl' in value) || value['debuggerUrl'] === undefined) return false;
    if (!('wsUrl' in value) || value['wsUrl'] === undefined) return false;
    return true;
}

export function CreateSessionResponseFromJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseFromJSONTyped(json, false);
}

export function CreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'sessionUrl': json['sessionUrl'],
        'debuggerFullscreenUrl': json['debuggerFullscreenUrl'],
        'debuggerUrl': json['debuggerUrl'],
        'wsUrl': json['wsUrl'],
    };
}

export function CreateSessionResponseToJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseToJSONTyped(json, false);
}

export function CreateSessionResponseToJSONTyped(value?: CreateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'sessionUrl': value['sessionUrl'],
        'debuggerFullscreenUrl': value['debuggerFullscreenUrl'],
        'debuggerUrl': value['debuggerUrl'],
        'wsUrl': value['wsUrl'],
    };
}
