/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunEvent } from './RunEvent';
import {
    RunEventFromJSON,
    RunEventFromJSONTyped,
    RunEventToJSON,
    RunEventToJSONTyped,
} from './RunEvent';

/**
 * 
 * @export
 * @interface ExecutionDetails
 */
export interface ExecutionDetails {
    /**
     * 
     * @type {string}
     * @memberof ExecutionDetails
     */
    runId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionDetails
     */
    urls?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionDetails
     */
    logs?: Array<string> | null;
    /**
     * Link to rrweb JSON/NDJSON in object storage.
     * @type {string}
     * @memberof ExecutionDetails
     */
    rrwebEvents?: string | null;
    /**
     * 
     * @type {Array<RunEvent>}
     * @memberof ExecutionDetails
     */
    llmSteps?: Array<RunEvent> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionDetails
     */
    screenshots?: Array<string> | null;
}

/**
 * Check if a given object implements the ExecutionDetails interface.
 */
export function instanceOfExecutionDetails(value: object): value is ExecutionDetails {
    return true;
}

export function ExecutionDetailsFromJSON(json: any): ExecutionDetails {
    return ExecutionDetailsFromJSONTyped(json, false);
}

export function ExecutionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'logs': json['logs'] == null ? undefined : json['logs'],
        'rrwebEvents': json['rrweb_events'] == null ? undefined : json['rrweb_events'],
        'llmSteps': json['llm_steps'] == null ? undefined : ((json['llm_steps'] as Array<any>).map(RunEventFromJSON)),
        'screenshots': json['screenshots'] == null ? undefined : json['screenshots'],
    };
}

export function ExecutionDetailsToJSON(json: any): ExecutionDetails {
    return ExecutionDetailsToJSONTyped(json, false);
}

export function ExecutionDetailsToJSONTyped(value?: ExecutionDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'urls': value['urls'],
        'logs': value['logs'],
        'rrweb_events': value['rrwebEvents'],
        'llm_steps': value['llmSteps'] == null ? undefined : ((value['llmSteps'] as Array<any>).map(RunEventToJSON)),
        'screenshots': value['screenshots'],
    };
}
