/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Health200Response
 */
export interface Health200Response {
    /**
     * 
     * @type {string}
     * @memberof Health200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the Health200Response interface.
 */
export function instanceOfHealth200Response(value: object): value is Health200Response {
    return true;
}

export function Health200ResponseFromJSON(json: any): Health200Response {
    return Health200ResponseFromJSONTyped(json, false);
}

export function Health200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Health200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function Health200ResponseToJSON(json: any): Health200Response {
    return Health200ResponseToJSONTyped(json, false);
}

export function Health200ResponseToJSONTyped(value?: Health200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}
