/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RunSummaryLinks } from './RunSummaryLinks';
import {
    RunSummaryLinksFromJSON,
    RunSummaryLinksFromJSONTyped,
    RunSummaryLinksToJSON,
    RunSummaryLinksToJSONTyped,
} from './RunSummaryLinks';

/**
 * 
 * @export
 * @interface RunSummary
 */
export interface RunSummary {
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    runId?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    site?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    status?: RunSummaryStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof RunSummary
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RunSummary
     */
    finishedAt?: Date | null;
    /**
     * 
     * @type {RunSummaryLinks}
     * @memberof RunSummary
     */
    links?: RunSummaryLinks;
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    sessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RunSummary
     */
    sessionLiveViewUrl?: string | null;
}


/**
 * @export
 */
export const RunSummaryStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type RunSummaryStatusEnum = typeof RunSummaryStatusEnum[keyof typeof RunSummaryStatusEnum];


/**
 * Check if a given object implements the RunSummary interface.
 */
export function instanceOfRunSummary(value: object): value is RunSummary {
    return true;
}

export function RunSummaryFromJSON(json: any): RunSummary {
    return RunSummaryFromJSONTyped(json, false);
}

export function RunSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'site': json['site'] == null ? undefined : json['site'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'finishedAt': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
        'links': json['links'] == null ? undefined : RunSummaryLinksFromJSON(json['links']),
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
        'sessionLiveViewUrl': json['session_live_view_url'] == null ? undefined : json['session_live_view_url'],
    };
}

export function RunSummaryToJSON(json: any): RunSummary {
    return RunSummaryToJSONTyped(json, false);
}

export function RunSummaryToJSONTyped(value?: RunSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'site': value['site'],
        'task_id': value['taskId'],
        'status': value['status'],
        'started_at': value['startedAt'] == null ? undefined : ((value['startedAt']).toISOString()),
        'finished_at': value['finishedAt'] === null ? null : ((value['finishedAt'] as any)?.toISOString()),
        'links': RunSummaryLinksToJSON(value['links']),
        'session_id': value['sessionId'],
        'session_live_view_url': value['sessionLiveViewUrl'],
    };
}
