/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentSuccessMetrics } from './AgentSuccessMetrics';
import {
    AgentSuccessMetricsFromJSON,
    AgentSuccessMetricsFromJSONTyped,
    AgentSuccessMetricsToJSON,
    AgentSuccessMetricsToJSONTyped,
} from './AgentSuccessMetrics';
import type { ScoreArtifactsInner } from './ScoreArtifactsInner';
import {
    ScoreArtifactsInnerFromJSON,
    ScoreArtifactsInnerFromJSONTyped,
    ScoreArtifactsInnerToJSON,
    ScoreArtifactsInnerToJSONTyped,
} from './ScoreArtifactsInner';

/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    runId?: string;
    /**
     * Parsed robots.txt checks relevant to the task.
     * @type {{ [key: string]: any; }}
     * @memberof Score
     */
    robotsTxtResults?: { [key: string]: any; };
    /**
     * 
     * @type {AgentSuccessMetrics}
     * @memberof Score
     */
    agentSuccessMetrics?: AgentSuccessMetrics;
    /**
     * Result payload returned by the agent for the task.
     * @type {{ [key: string]: any; }}
     * @memberof Score
     */
    taskResponse?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof Score
     */
    scoreFinal?: number;
    /**
     * 
     * @type {Array<ScoreArtifactsInner>}
     * @memberof Score
     */
    artifacts?: Array<ScoreArtifactsInner>;
}

/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value: object): value is Score {
    return true;
}

export function ScoreFromJSON(json: any): Score {
    return ScoreFromJSONTyped(json, false);
}

export function ScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Score {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'robotsTxtResults': json['robots_txt_results'] == null ? undefined : json['robots_txt_results'],
        'agentSuccessMetrics': json['agent_success_metrics'] == null ? undefined : AgentSuccessMetricsFromJSON(json['agent_success_metrics']),
        'taskResponse': json['task_response'] == null ? undefined : json['task_response'],
        'scoreFinal': json['score_final'] == null ? undefined : json['score_final'],
        'artifacts': json['artifacts'] == null ? undefined : ((json['artifacts'] as Array<any>).map(ScoreArtifactsInnerFromJSON)),
    };
}

export function ScoreToJSON(json: any): Score {
    return ScoreToJSONTyped(json, false);
}

export function ScoreToJSONTyped(value?: Score | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['runId'],
        'robots_txt_results': value['robotsTxtResults'],
        'agent_success_metrics': AgentSuccessMetricsToJSON(value['agentSuccessMetrics']),
        'task_response': value['taskResponse'],
        'score_final': value['scoreFinal'],
        'artifacts': value['artifacts'] == null ? undefined : ((value['artifacts'] as Array<any>).map(ScoreArtifactsInnerToJSON)),
    };
}
