/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentStatus,
  CreateSessionRequest,
  CreateSessionResponse,
  ExecutionDetails,
  Health200Response,
  ListEvents200Response,
  RobotsAnalysisRequest,
  RobotsAnalysisResponse,
  RunRequest,
  RunResponse,
  RunSummary,
  ScoreDetail,
} from '../models/index';
import {
    AgentStatusFromJSON,
    AgentStatusToJSON,
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    CreateSessionResponseFromJSON,
    CreateSessionResponseToJSON,
    ExecutionDetailsFromJSON,
    ExecutionDetailsToJSON,
    Health200ResponseFromJSON,
    Health200ResponseToJSON,
    ListEvents200ResponseFromJSON,
    ListEvents200ResponseToJSON,
    RobotsAnalysisRequestFromJSON,
    RobotsAnalysisRequestToJSON,
    RobotsAnalysisResponseFromJSON,
    RobotsAnalysisResponseToJSON,
    RunRequestFromJSON,
    RunRequestToJSON,
    RunResponseFromJSON,
    RunResponseToJSON,
    RunSummaryFromJSON,
    RunSummaryToJSON,
    ScoreDetailFromJSON,
    ScoreDetailToJSON,
} from '../models/index';

export interface AnalyzeRobotsRequest {
    robotsAnalysisRequest: RobotsAnalysisRequest;
}

export interface CreateRunRequest {
    runRequest: RunRequest;
}

export interface CreateSessionOperationRequest {
    createSessionRequest: CreateSessionRequest;
}

export interface GetExecutionDetailsRequest {
    runId: string;
}

export interface GetRunRequest {
    runId: string;
}

export interface GetRunStatusRequest {
    runId: string;
}

export interface GetScoreRequest {
    runId: string;
}

export interface ListEventsRequest {
    runId: string;
    cursor?: string | null;
    limit?: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Analyze robots.txt compliance for a set of visited URLs
     */
    async analyzeRobotsRaw(requestParameters: AnalyzeRobotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotsAnalysisResponse>> {
        if (requestParameters['robotsAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'robotsAnalysisRequest',
                'Required parameter "robotsAnalysisRequest" was null or undefined when calling analyzeRobots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/robots/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RobotsAnalysisRequestToJSON(requestParameters['robotsAnalysisRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotsAnalysisResponseFromJSON(jsonValue));
    }

    /**
     * Analyze robots.txt compliance for a set of visited URLs
     */
    async analyzeRobots(requestParameters: AnalyzeRobotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotsAnalysisResponse> {
        const response = await this.analyzeRobotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new run
     */
    async createRunRaw(requestParameters: CreateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunResponse>> {
        if (requestParameters['runRequest'] == null) {
            throw new runtime.RequiredError(
                'runRequest',
                'Required parameter "runRequest" was null or undefined when calling createRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/runs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunRequestToJSON(requestParameters['runRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunResponseFromJSON(jsonValue));
    }

    /**
     * Start a new run
     */
    async createRun(requestParameters: CreateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunResponse> {
        const response = await this.createRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Session
     */
    async createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>> {
        if (requestParameters['createSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSessionRequest',
                'Required parameter "createSessionRequest" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/session/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create Session
     */
    async createSession(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get execution details (URLs, logs, rrweb, LLM steps, screenshots)
     */
    async getExecutionDetailsRaw(requestParameters: GetExecutionDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutionDetails>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getExecutionDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/runs/{run_id}/execution_details`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutionDetailsFromJSON(jsonValue));
    }

    /**
     * Get execution details (URLs, logs, rrweb, LLM steps, screenshots)
     */
    async getExecutionDetails(requestParameters: GetExecutionDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutionDetails> {
        const response = await this.getExecutionDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get run status and summary
     */
    async getRunRaw(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunSummary>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/runs/{run_id}`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunSummaryFromJSON(jsonValue));
    }

    /**
     * Get run status and summary
     */
    async getRun(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunSummary> {
        const response = await this.getRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get agent status for polling
     */
    async getRunStatusRaw(requestParameters: GetRunStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatus>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getRunStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/runs/{run_id}/status`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentStatusFromJSON(jsonValue));
    }

    /**
     * Get agent status for polling
     */
    async getRunStatus(requestParameters: GetRunStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatus> {
        const response = await this.getRunStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get final score and detailed metrics
     */
    async getScoreRaw(requestParameters: GetScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScoreDetail>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling getScore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/runs/{run_id}/score`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScoreDetailFromJSON(jsonValue));
    }

    /**
     * Get final score and detailed metrics
     */
    async getScore(requestParameters: GetScoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScoreDetail> {
        const response = await this.getScoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Health200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Health200ResponseFromJSON(jsonValue));
    }

    /**
     * Health check
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Health200Response> {
        const response = await this.healthRaw(initOverrides);
        return await response.value();
    }

    /**
     * List step of events
     */
    async listEventsRaw(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEvents200Response>> {
        if (requestParameters['runId'] == null) {
            throw new runtime.RequiredError(
                'runId',
                'Required parameter "runId" was null or undefined when calling listEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/runs/{run_id}/events`;
        urlPath = urlPath.replace(`{${"run_id"}}`, encodeURIComponent(String(requestParameters['runId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEvents200ResponseFromJSON(jsonValue));
    }

    /**
     * List step of events
     */
    async listEvents(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEvents200Response> {
        const response = await this.listEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
