/* tslint:disable */
/* eslint-disable */
/**
 * Agent Navigability Simulator API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSessionRequest,
  CreateSessionResponse,
  EvaluationDetailsRequest,
  EvaluationDetailsResponse,
  RobotsAnalysisRequest,
  RobotsAnalysisResponse,
  RunRequest,
  RunResponse,
} from '../models/index';
import {
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    CreateSessionResponseFromJSON,
    CreateSessionResponseToJSON,
    EvaluationDetailsRequestFromJSON,
    EvaluationDetailsRequestToJSON,
    EvaluationDetailsResponseFromJSON,
    EvaluationDetailsResponseToJSON,
    RobotsAnalysisRequestFromJSON,
    RobotsAnalysisRequestToJSON,
    RobotsAnalysisResponseFromJSON,
    RobotsAnalysisResponseToJSON,
    RunRequestFromJSON,
    RunRequestToJSON,
    RunResponseFromJSON,
    RunResponseToJSON,
} from '../models/index';

export interface AnalyzeRobotsRequest {
    robotsAnalysisRequest: RobotsAnalysisRequest;
}

export interface CreateRunRequest {
    runRequest: RunRequest;
}

export interface CreateSessionOperationRequest {
    createSessionRequest: CreateSessionRequest;
}

export interface EvaluateTaskRequest {
    evaluationDetailsRequest: EvaluationDetailsRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Analyze robots.txt compliance
     */
    async analyzeRobotsRaw(requestParameters: AnalyzeRobotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RobotsAnalysisResponse>> {
        if (requestParameters['robotsAnalysisRequest'] == null) {
            throw new runtime.RequiredError(
                'robotsAnalysisRequest',
                'Required parameter "robotsAnalysisRequest" was null or undefined when calling analyzeRobots().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/robots/analyze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RobotsAnalysisRequestToJSON(requestParameters['robotsAnalysisRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RobotsAnalysisResponseFromJSON(jsonValue));
    }

    /**
     * Analyze robots.txt compliance
     */
    async analyzeRobots(requestParameters: AnalyzeRobotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RobotsAnalysisResponse> {
        const response = await this.analyzeRobotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new run
     */
    async createRunRaw(requestParameters: CreateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunResponse>> {
        if (requestParameters['runRequest'] == null) {
            throw new runtime.RequiredError(
                'runRequest',
                'Required parameter "runRequest" was null or undefined when calling createRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/runs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunRequestToJSON(requestParameters['runRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunResponseFromJSON(jsonValue));
    }

    /**
     * Start a new run
     */
    async createRun(requestParameters: CreateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunResponse> {
        const response = await this.createRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a browser session
     */
    async createSessionRaw(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSessionResponse>> {
        if (requestParameters['createSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSessionRequest',
                'Required parameter "createSessionRequest" was null or undefined when calling createSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/session/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create a browser session
     */
    async createSession(requestParameters: CreateSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSessionResponse> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Evaluate task for a run
     */
    async evaluateTaskRaw(requestParameters: EvaluateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvaluationDetailsResponse>> {
        if (requestParameters['evaluationDetailsRequest'] == null) {
            throw new runtime.RequiredError(
                'evaluationDetailsRequest',
                'Required parameter "evaluationDetailsRequest" was null or undefined when calling evaluateTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/runs/evaluate_task`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EvaluationDetailsRequestToJSON(requestParameters['evaluationDetailsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvaluationDetailsResponseFromJSON(jsonValue));
    }

    /**
     * Evaluate task for a run
     */
    async evaluateTask(requestParameters: EvaluateTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvaluationDetailsResponse> {
        const response = await this.evaluateTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
